version: "3.5"

networks:
  default:
    name: example.com

services:
  master:
    image: jcrist/hadoop-testing-cdh6
    user: root
    environment:
      - HADOOP_TESTING_CONFIG=${HADOOP_TESTING_CONFIG:-simple}
    command: /root/startup.sh /etc/master.supervisord.conf
    container_name: master
    hostname: master
    domainname: example.com
    ports:
      - 8020:8020    # NN
      - 9000:9000    # NN
      - 50070:50070  # NN webui
      - 8088:8088    # RM webui
    tmpfs:
      - /tmp:noexec
