name: ray on yarn CI
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - run: ls -l .
      - run: docker-compose -f ./continuous_integration/action/docker-compose.yml up -d
      - run: docker ps
